---
title: "SMS"
author: "Bryan Polito"
date: "`r Sys.Date()`"
output:
  html_document:
    css: style.css
---

```{r librerias, include=FALSE}
#carga de librerías
library(openxlsx)
library(readxl)
library(tidyverse)
library(kableExtra)
```

```{r ruta, echo=FALSE}
#Establecer ruta
setwd("C:/Users/COPERVA/Desktop/SMS")
```

```{r carga, echo=FALSE}
# Carga de bases
base <- read_excel("base.xlsx")
base <- select(base, 1:3)
layout <- read_excel("layout.xlsx")
```

### Carga de base

```{r base, echo=FALSE}
kableExtra::kable(head(base), format = "html") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left")

```

```{r variables, echo=FALSE}
# Cambio de nombres en las columnas
colnames(base) <- c("Telefono", "mensaje", "Cuenta")
colnames(layout) <- c("Telefono", "mensaje", "Cuenta")
```

```{r combinada, echo=FALSE}
# Se junta el layout y la base
combined <- rbind(layout, base)
```

```{r extraccion, include=FALSE}
# Se extrae el primer registro

combined$mensaje <- ifelse(is.na(combined$mensaje), base$mensaje[!is.na(base$mensaje)][1], combined$mensaje)
combined$Cuenta <- ifelse(is.na(combined$Cuenta), base$Cuenta[!is.na(base$Cuenta)][1], combined$Cuenta)

# Se busca si algún registro excede los 160 carcateres
combined$excede_limite <- nchar(combined$mensaje) > 160
exceden <- sum(as.numeric(combined$excede_limite))
no_exceden <- sum(as.numeric(!combined$excede_limite))
combined <- subset(combined, select = -excede_limite)
```

### Suma de registros que exceden los 160 caracateres:

```{r suma_exceden, echo=FALSE}
print(exceden)
```

### Suma de registros que no exceden los 160 caracteres:

```{r suma_no_exceden, echo=FALSE}
print(no_exceden)
```

### Limpieza de datos

```{r limpieza, echo=FALSE}
#Se quitan espacios y se transforma en variables de tipo texto
combined$Telefono <- gsub("\\s+", "", as.character(combined$Telefono))
combined$Cuenta <- gsub("\\s+", "", as.character(combined$Cuenta))
combined[] <- lapply(combined, function(x) {
    x <- str_replace_all(x, "[áäâà]", "a")
    x <- str_replace_all(x, "[éëêè]", "e")
    x <- str_replace_all(x, "[íïîì]", "i")
    x <- str_replace_all(x, "[óöôò]", "o")
    x <- str_replace_all(x, "[úüûù]", "u")
    x <- str_replace_all(x, "[ñ]", "n")
    return(x)
  })
kableExtra::kable(head(combined, n= 10), format = "html") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left")

```

```{r NA, echo=FALSE}
# Eliminar filas con NA
combined <-  na.omit(combined)
```

```{r salida, echo=FALSE}
# Guardar el xlsx
  datos_final <- write.xlsx(combined, "SKY2_SMS_06062023.xlsx")
```
